### ISSUE TITLE
Reading metric fails with IllegalStateException on spark-2.x branch

### ISSUE THREAD

**Issue by asavartsov** [CGnal/spark-opentsdb#5]
When I try to read some data from OpenTSDB using code from spark-2.x branch I get the `IllegalStateException: Object has already been returned to this pool or is invalid`. This error does not occur when I use library from master branch on the same setup (code from master branch was slightly modified to compile with Spark 2.1 and Scala 2.11, nothing special).

If I turn on TRACE level logging, I can see duplicate messages `iterating done, returning the TSDB client instance to the pool`, apparently something calls `hasNext` on the iterator twice. Not sure if it's a good solution, but I replaced the code at line 349 of OpenTSDBContext.scala with

```scala
try {
  TSDBClientManager.pool.returnObject(tsdb)
} catch {
  case _: java.lang.IllegalStateException =>
}
```

and it worked.

Executor logs:

```
2017-03-24 14:14:02,226 INFO  [Executor task launch worker-0] executor.Executor: Running task 0.1 in stage 1.0 (TID 5)
2017-03-24 14:14:02,234 INFO  [Executor task launch worker-0] rdd.NewHadoopRDD: Input split: HBase table split(table name: tsdb, scan: GggAAAABWJMDICIIAAAAAViTAyEqjwEKKG9yZy5hcGFjaGUuaGFkb29wLmhiYXNlLmZpbHRlci5S
b3dGaWx0ZXISYwphCAISXQo0b3JnLmFwYWNoZS5oYWRvb3AuaGJhc2UuZmlsdGVyLlJlZ2V4U3Ry
aW5nQ29tcGFyYXRvchIlChReXHgwMFx4MDBceDAwXHgwMS4rJBAgGgVVVEYtOCIESkFWQTgBQAE=, start row: \x00\x00\x00\x01X\x93\x03 , end row: \x00\x00\x00\x01X\x93\x03!, region location: ion-node-03.infocom.local, encoded region name: 33692863ccca3795b31d59ecaf48111a)
2017-03-24 14:14:02,236 INFO  [Executor task launch worker-0] zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x2eaa31a2 connecting to ZooKeeper ensemble=localhost:2181
2017-03-24 14:14:02,236 INFO  [Executor task launch worker-0] zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x2eaa31a20x0, quorum=localhost:2181, baseZNode=/hbase
2017-03-24 14:14:02,241 INFO  [Executor task launch worker-0-SendThread(localhost:2181)] zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2017-03-24 14:14:02,242 INFO  [Executor task launch worker-0-SendThread(localhost:2181)] zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
2017-03-24 14:14:02,245 INFO  [Executor task launch worker-0-SendThread(localhost:2181)] zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x35afb4a7e6000be, negotiated timeout = 40000
2017-03-24 14:14:02,247 INFO  [Executor task launch worker-0] mapreduce.TableInputFormatBase: Input split length: 4 M bytes.
2017-03-24 14:14:02,425 INFO  [Executor task launch worker-0] client.ConnectionManager$HConnectionImplementation: Closing zookeeper sessionid=0x35afb4a7e6000be
2017-03-24 14:14:02,427 INFO  [Executor task launch worker-0-EventThread] zookeeper.ClientCnxn: EventThread shut down
2017-03-24 14:14:02,427 INFO  [Executor task launch worker-0] zookeeper.ZooKeeper: Session: 0x35afb4a7e6000be closed
2017-03-24 14:14:02,438 INFO  [Executor task launch worker-0] opentsdb.TSDBClientFactory: About to flush the TSDB client instance
2017-03-24 14:14:02,438 INFO  [Executor task launch worker-0] opentsdb.TSDBClientFactory: About to flush the TSDB client instance: done
2017-03-24 14:14:02,438 ERROR [Executor task launch worker-0] executor.Executor: Exception in task 0.1 in stage 1.0 (TID 5)
IllegalStateException: Object has already been returned to this pool or is invalid
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:551)
	at com.cgnal.spark.opentsdb.OpenTSDBContext$$anonfun$14$$anon$2.hasNext(OpenTSDBContext.scala:349)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:30)
	at org.spark_project.guava.collect.Ordering.leastOf(Ordering.java:670)
	at org.apache.spark.util.collection.Utils$.takeOrdered(Utils.scala:37)
	at org.apache.spark.rdd.RDD$$anonfun$takeOrdered$1$$anonfun$30.apply(RDD.scala:1422)
	at org.apache.spark.rdd.RDD$$anonfun$takeOrdered$1$$anonfun$30.apply(RDD.scala:1419)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Reading code is the same as one in #4

**Comment by dgreco** [comment]
Good catch,
I’ll commit this modification in the master.
Thanks.
David

**Comment by dgreco** [comment]
I'll check the issue, in principle it shouldn't call hasNext twice, just to be sure that there is nothing more serious behind.

**Comment by gumplus** [comment]
@dgreco  Hey man. Is this library supporting Spark2 version? And  can you give a example? Thank you!
